Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -66,7 +66,10 @@ jobs:
         timeout-minutes: 1
         
       - name: Generate coverage report
-        run: npm run test:coverage
+         run: |
+          npm runtest:coverage -- --watch=false || (echo "Timeout or disconnection error, stopping..." && exit 1)
+        working-directory: 'GithubActions/'
+        timeout-minutes: 1
 
 
       - name: Upload coverage report
